### PR TITLE
Use parallel repair strategy

### PR DESCRIPTION
**Pull request by tehhowch**
- Resolves the merge conflict for endless-sky#1971
 - Implements a parallel recharging strategy for carried ships, prioritizing the ship with the most need rather than sequentially by bay.
 - Fixes a bug I introduced earlier, in 05e6043fb775188f571547f666786ff442b1fb40, in which carried ships did not get to use their own repair functionality once the parent had no additional excess repair.

### CODE REVIEW

**Comment by Pointedstick** [comment]
@zwparchman, any word on this?

**Comment by tehhowch** [comment]
I should actually close this and wait for endless-sky#3182 to merge before resolving any conflicts, as that version of this functionality is better.

**Comment by zwparchman** [comment]
I'll try to get to this soon, but turnung a hew hundred commits into a hand
full might take a while and I want to make sure I can do it in one session.

**Comment by tehhowch** [comment]
@zwparchman I've closed this pull as we wait for endless-sky#3182 to be merged. After that, there will definitely be some conflicts that we need to address, but they should be fairly simple to do if we avoid rebasing.

**Pull request closed without merging**
