### PR TITLE
Extend re-arming logic to encompass situational docking

### PR DESCRIPTION
**Pull request by tehhowch**
If you prefer, I can PR to upstream directly. Your base commits are included so no worries :)

### CODE REVIEW

**Comment by tehhowch** [comment]
I haven't fully tested the logic branches for recalling, and wouldn't mind more eyes on this (in case @Elyssaen is feeling kind)

**Comment by tehhowch** [comment]
I'm feeling happy with the current logic overall:
One possible shortfall is if the fighter is armed with two different ammo types: if the parent cannot supply one of the two, but has plenty of the other, the fighter won't board solely to re-arm. It would still board for low HP, refueling, or full cargo though, and when launching, it would obtain the ammo that it could use.

edit: here's a better link for comparing what has happened, without all the stuff from `master`:
https://github.com/endless-sky/endless-sky/compare/master...tehhowch:SituationalFighterDocking

**Comment by zwparchman** [comment]
Taking ammo from cargo was not an error it was intentional. If I'm missing a detail about the outfits vs cargo in this case please let me know as the intention was to let the carrier provide ammo that the carrier itself could not use and to not need an outfitter to rearm the fighter over and over until all of the carriers missiles were gone. 

I'm still reviewing the pull, but it seems mostly fine. I'm having some "fun" finding out how to make git bend to my will, but I should have most of your changes incorporated soon.

**Comment by tehhowch** [comment]
Two issues with taking from cargo: 1) there is no guarantee the carrier is
the one that received the missiles/ammo bought into cargo, and 2) the
addition of ammo as a rare flotsam means you could "restock" your carriers
without landing, e.g. "infinite missiles per day", if they were picking up
enough debris on the battlefield.

To have the carrier hold the specific ammo for its fighters in its outfit
space is just a matter of buying the appropriate storage racks - one is
able to guarantee that the carrier has the ammo, and that the ammo is
restocked for the fighters and the stockpile when your fleet finally
touches down.
IMO drawing from outfits is a more balanced approach as well (something MZ
will appreciate), because the player will have to decide how to gear their
carriers: rather than just use all outfit space for weapons and shields,
and cargo for fighter ammo, some capability of the carrier must be traded
in order to support the fighters.

I'll share a test mission tomorrow of two appropriately geared Skein+Finch
squadrons that show off some of the behavior added by our work.

**Comment by tehhowch** [comment]
Here's a test mission (in Hai space so it's generally just you + the NPC + the target):
[fighter_reboarding_test.txt](https://github.com/zwparchman/endless-sky/files/1151161/fighter_reboarding_test.txt)


One thing this PR would draw attention to is that dual-armament fighters would not re-arm themselves if their parent (currently not selectable by the player) wasn't a ship in your fleet that had what they needed. For example, if you get the double-skein variant, only the fighters assigned to the ammo skein will intentionally top off their missile ammo, even though the ammo skein has enough surplus to supply the other fighters as well.
This means that if a player has a hybrid fighter complement, where some use ammo X and others use ammo Y, the carriers need to have both X and Y to be helpful, as they may parent either of the type fighter types.

**Comment by tehhowch** [comment]
How goes it?

**Comment by zwparchman** [comment]
The status is merged. I left a define to switch between outfit and cargo reloading with outfit being the default.

**Pull request merged**
